---
title: Garrett Boatman
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
tagline: Web Designer & Developer | Sacramento, CA
url: http://garrettboatman.com
socialimg: "/img/social.jpg"
facebook: gboatman
twitter: garrettboatman
github: garrettboatman
googleplus: GarrettBoatman
instagram: garrettboatman
rdio: garrettboatman
spotify: garrettboatman
phone: 916-276-1044
email: hello@garrettboatman.com
sass:
  sass_dir: scss
  style: compressed
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
