# Site settings
title: Garrett Boatman
tagline: "Web Designer & Developer | Sacramento, CA"
url: "http://garrettboatman.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: gboatman
twitter: garrettboatman
github: garrettboatman
googleplus: 
instagram: garrettboatman

# Contact
phone: "916-276-1044" # This is my real number. You should text me.
email: "hello@garrettboatman.com" # This is my real email address. Please don't email me.

sass:
  sass_dir: scss
  style: :compressed
  
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]