---
title: Garrett Boatman | Developer, designer, problem solver | Los Angeles, CA
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: Garrett Boatman | Developer, designer, problem solver | Los Angeles, CA
url: https://garrettboatman.com
socialimg: "/img/social.jpg"
facebook: gboatman
twitter: garrettboatman
github: garrettboatman
googleplus: GarrettBoatman
instagram: garrettboatman
rdio: garrettboatman
spotify: garrettboatman

# Contact
phone: "916-276-1044" # This is my real number. You should text me.
email: "hello@garrettboatman.com" # This is my real email address. Please don't email me.

sass:
  sass_dir: scss
  style: compressed
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
